{"variants":[{"paths":["\/documentation\/passage\/oauth2api\/modelerror_oauth2callback\/invalidrequestobject"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/Passage\/documentation\/Passage","doc:\/\/Passage\/documentation\/Passage\/OAuth2API","doc:\/\/Passage\/documentation\/Passage\/OAuth2API\/ModelError_oauth2Callback"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidRequestObject","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidRequestObject"}],"title":"OAuth2API.ModelError_oauth2Callback.invalidRequestObject","roleHeading":"Case","modules":[{"name":"Passage"}],"role":"symbol","symbolKind":"case","externalID":"s:7Passage9OAuth2APIC25ModelError_oauth2CallbackO20invalidRequestObjectyA2EmF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/Passage\/documentation\/Passage\/OAuth2API\/ModelError_oauth2Callback\/invalidRequestObject"},"sections":[],"references":{"doc://Passage/documentation/Passage":{"role":"collection","title":"Passage","abstract":[{"type":"text","text":"Use Passage to add exclusively Passwordless authentication to your iOS Application."}],"kind":"symbol","type":"topic","url":"\/documentation\/passage","identifier":"doc:\/\/Passage\/documentation\/Passage"},"doc://Passage/documentation/Passage/OAuth2API":{"identifier":"doc:\/\/Passage\/documentation\/Passage\/OAuth2API","type":"topic","url":"\/documentation\/passage\/oauth2api","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OAuth2API","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OAuth2API"}],"title":"OAuth2API","role":"symbol","kind":"symbol","abstract":[]},"doc://Passage/documentation/Passage/OAuth2API/ModelError_oauth2Callback":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ModelError_oauth2Callback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ModelError_oauth2Callback"}],"title":"OAuth2API.ModelError_oauth2Callback","abstract":[{"type":"text","text":"enum for parameter error"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/Passage\/documentation\/Passage\/OAuth2API\/ModelError_oauth2Callback","url":"\/documentation\/passage\/oauth2api\/modelerror_oauth2callback"},"doc://Passage/documentation/Passage/OAuth2API/ModelError_oauth2Callback/invalidRequestObject":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidRequestObject","kind":"identifier"}],"title":"OAuth2API.ModelError_oauth2Callback.invalidRequestObject","kind":"symbol","identifier":"doc:\/\/Passage\/documentation\/Passage\/OAuth2API\/ModelError_oauth2Callback\/invalidRequestObject","type":"topic","url":"\/documentation\/passage\/oauth2api\/modelerror_oauth2callback\/invalidrequestobject","role":"symbol","abstract":[]}}}